pygments: true
relative_permalinks: false
name: VitalElement
description: Simplicity in embedded software dvelopement. IDE and tools.
gh-blob-url: https://github.com/jameswalmsley/bitthunder/blob/master
url: http://vitalelement.github.io

